import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import { FsmRenderer } from "../fsm-renderer/FsmRenderer";
import styles from "../styles/Home.module.css";

// const ComponentWithNoSSR = dynamic(
//   () => import('../fsm-renderer/FsmRenderer'),
//   { ssr: false }
// )

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Passage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <FsmRenderer />
      </main>
    </div>
  );
};

export default Home;
